### ISSUE TITLE
fix error on mp4 uploads

### ISSUE THREAD

**Issue by nathan-power** [Satellite-im/Core-PWA#4915]
https://issues.satellite.im/b/bugs/mp4-upload/

**Comment by stavares843** [comment]
works fine for me

**Comment by nathan-power** [comment]
Was it fixed? There might be a condition that sometimes causes a failed upload

**Comment by stavares843** [comment]
no one fixed it but never had that issue here, at least on my mac using Chrome

the issue I had with uploads was a different one that hogan also had that when sending files they appear invisible


![image](https://user-images.githubusercontent.com/29093946/190857725-0f98be41-11da-4b40-972d-8cb2a6cf78bc.png)

**Comment by stavares843** [comment]
more users reached out about the files not being visible on chat as well

**Comment by stavares843** [comment]
works fine now
