### ISSUE TITLE
settings - timezone

### ISSUE THREAD

**Issue by molimauro** [Satellite-im/Core-PWA#5207]
remove timezone option and the `vvo/tzdb` package

**Comment by josephmcg** [comment]
will rip it out and use new utility functions

**Comment by molimauro** [comment]
A nice (i think) related feature would be the possibility for the user to see receivers messages datetime in the receiver timezone.
That could help when messaging with people with different timezones

**Comment by josephmcg** [comment]
use this new timestamp util instead of vuex version (mapGetters). You can do a project search 
`utilities/timestamp.ts`

This component is using new utils
`components/views/navigation/sidebar/list/item/Item.vue`

you can delete this utility and associated package
`utilities/Timezone.ts`

you can delete these getters, and the associated store value, type, and mutation
`store/settings/getters.ts`

**Comment by josephmcg** [comment]
https://github.com/Satellite-im/Core-PWA/pull/5384
